name: 'Example of zeus on vulcan'
on:
  push:
    branches: develope,2.11.x
  pull_request:
    branches: master
  schedule:
    cron: '* * * * *'
    repeat: every-day/every-hour
jobs:
  Build-And-Publish:
    - name: 'Build and publish'
      run-on: 'docker-image'
      #os: linux or darwin or wins
      #arch: amd64
      #artifacts:
      #  - {host}:{target}
      args:
        Revision: '1.0.0'
      steps:
        - name: 'Build'
          run: 'mvn clean install -U -Drevision={{.Revision}}'
        - name: 'Deploy to jfrog'
          use: 'plugin/deploy-to-jfrog'
          with:
            path: 'target/file'
            username: '$USERNAME'
            password: '$PASSWORD'
